name: call-webhook
on: pull_request_target

jobs:
  pr-check:
    name: Check PR
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Setup Action
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: some command
        env:
          PAYLOAD: ${{ secrets.PAYLOAD }}
        run: |
          npm run test -- "${PAYLOAD}"